# Generated by Django 2.2.2 on 2019-07-20 15:46

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('users', '0006_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
