# Generated by Django 2.2.2 on 2019-07-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190720_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
