# Generated by Django 2.2.2 on 2019-07-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190721_1431'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='profile',
        ),
    ]
