# Generated by Django 2.2.2 on 2019-07-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190721_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='usertype',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
