# Generated by Django 2.2.2 on 2019-07-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190721_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='usertype',
            new_name='user_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='manager_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='restaurant_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
