# Generated by Django 2.2.2 on 2019-07-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
