# Generated by Django 2.2.2 on 2019-07-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_feedback_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
