# Generated by Django 2.2.2 on 2019-07-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20190720_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
