# Generated by Django 2.2.2 on 2019-07-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='cost',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='food_pics'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
