# Generated by Django 2.2.3 on 2019-07-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20190726_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='food',
            name='cost',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
