# Generated by Django 2.2.3 on 2019-07-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20190731_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='food_pics/'),
        ),
    ]
