# Generated by Django 2.2.3 on 2019-08-01 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20190801_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
